[workspace]
changelog_update = true
git_release_enable = false
git_tag_enable = false
publish = false
semver_check = true

[[package]]
name = "lanyard-ssh-agent"
changelog_path = "CHANGELOG.md"
git_tag_name = "v{{ version }}"
