name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: jwilger/gha-workflows/.github/workflows/rust-release-plz.yml@ac22efd2f7744a9c80f995549193716e751c77a3
    secrets:
      op-service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
